package org.black_ixx.bossshop.events;

import org.black_ixx.bossshop.core.BSBuy;
import org.black_ixx.bossshop.core.BSShop;
import org.bukkit.entity.Player;
import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;

public class BSPlayerPurchasedEvent extends Event{

    private static final HandlerList handlers=new HandlerList();
    private final Player player;
    private final BSBuy buy;
    private final BSShop shop;

    public BSPlayerPurchasedEvent(Player player,BSShop shop,BSBuy buy){
        this.player=player;
        this.buy=buy;
        this.shop=shop;
    }

    public Player getPlayer(){
        return player;
    }

    public BSBuy getShopItem(){
        return buy;
    }

    public BSShop getShop(){
        return shop;
    }

    public static HandlerList getHandlerList(){
        return handlers;
    }

    @Override
    public HandlerList getHandlers(){
        return handlers;
    }

}
